version: "3"
services:
 
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - document-streaming

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'          # 9092 is the internal port that can be used within the docker network
      - '9093:9093'          # 9093 is the external port to access from your local machine
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT     
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093                              # 9092 will be for other containers, 9093 for your local machine
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093     # 9092 will be for other containers, 9093 for your local machine
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - document-streaming

  spark:
    image: 'jupyter/pyspark-notebook:spark-2'
    ports:
      - '8888:8888'
      - "4040-4080:4040-4080"
    volumes:
      - ./pyspark-notebook:/home/jovyan/work
    networks:
      - document-streaming

  data-api:
    image: 'data-api'
    ports:
       - '80:80'
    networks:
      - document-streaming

  mongo:
    image: mongo
    volumes:
      - ./mongodb-data:/data/db    
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: auth
    networks:
      - document-streaming

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: tribes
    networks:
      - document-streaming
    depends_on:
      - mongo


networks:
  document-streaming:
    driver: bridge
  